/* USER TYPES */
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESSFUL = 'USER_LOGOUT_SUCCESSFUL';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_LOADING = 'USER_LOADING';
/* WELLS TYPES */
export const GET_WELLS_SUCCESSFUL = 'GET_WELLS_SUCCESSFUL';
export const GET_WELLS_FAIL = 'GET_WELL_FAIL';
export const WELLS_LOADING = 'WELLS_LOADING';
/* WELL DETAILS TYPES */
export const GET_ONE_WELL_SUCCESSFUL = 'GET_ONE_WELL_SUCCESSFULL';
export const GET_ONE_WELL_READINGS_SUCCESSFUL =
    'GET_ONE_WELL_READINGS_SUCCESSFUL';
export const GET_ONE_WELL_FAIL = 'GET_ONE_WELL_FAIL';
export const GET_ONE_WELL_READING_FAIL = 'GET_ONE_WELL_READING_FAIL';
export const ONE_WELL_LOADING = 'ONE_WELL_LOADING';
