/* USER TYPES */
const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
const USER_LOADING = 'USER_LOADING';
/* WELLS TYPES */
const GET_WELLS_SUCCESSFUL = 'GET_WELLS_SUCCESSFUL';
const GET_WELLS_FAIL = 'GET_WELL_FAIL';
const WELLS_LOADING = 'WELLS_LOADING';
/* WELL DETAILS TYPES */
const GET_ONE_WELL_SUCCESSFUL = 'GET_ONE_WELL_SUCCESSFULL';
const GET_ONE_WELL_READINGS_SUCCESSFUL = 'GET_ONE_WELL_READINGS_SUCCESSFUL';
const GET_ONE_WELL_FAIL = 'GET_ONE_WELL_FAIL';
const GET_ONE_WELL_READING_FAIL = 'GET_ONE_WELL_READING_FAIL';
const ONE_WELL_LOADING = 'ONE_WELL_LOADING';
